[package]
name = "marigold_vk"
version = "0.1.0"
edition = "2024"

[build-dependencies]
regex = "1.13.1"
chrono = "0.4.45"
rayon.workspace = true

[dependencies]
# rendering
vulkano.workspace = true
winit = "0.30.13"

# game engine stuff
bevy_ecs = { version = "0.19.1", features = ["debug"] }
glam.workspace = true
gltf.workspace = true

# logging
env_logger = "0.11.11"
log.workspace = true

# general utility
anyhow.workspace = true
derived-deref.workspace = true
rayon.workspace = true
itertools = "0.15.0"

# data manipulation
bytemuck.workspace = true

# noise & random
rand.workspace = true

# workspace dependencies
bvh = { path = "../bvh" }
mesh_interface = { path = "../mesh_interface" }
gltf_loading = { path = "../gltf_loading" }
