[package]
name = "marigold_vk"
version = "0.1.0"
edition = "2024"

[build-dependencies]
regex = "1.12.2"
chrono = "0.4.42"
rayon = "1.11.0"

[dependencies]
# rendering
vulkano = { git = "https://github.com/vulkano-rs/vulkano", rev = "fb1096f" }
winit = "0.30.13"

# game engine stuff
bevy_ecs = { version = "0.18.1", features = ["debug"] }
glam = "0.30.9"
gltf = "1.4.1"

# # user interface

# logging
env_logger = "0.11.8"
log = "0.4.29"

# general utility
# pollster = "0.4.0"
anyhow = "1.0.100"
derived-deref = "2.1.0"
rayon = "1.11.0"
itertools = "0.15.0"

# data manipulation
gpu_layout = "0.2.2"
bytemuck = "1.24.0"

# noise & random
rand = "0.9.2"

# workspace dependencies
bvh = { path = "../bvh" }
mesh_interface = { path = "../mesh_interface" }
gltf_loading = { path = "../gltf_loading" }
